### ISSUE TITLE
Warning: Trying to access array offset on value of type null in book_prev()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/book_menus#3]
When I view the main page of a sample book:

> Warning: Trying to access array offset on value of type null in book_prev() (line 774 of /app/httpdocs/core/modules/book/book.module).

If I disable the module I don't get the error. It doesn't change if I update the settings to add the book to the menu.

I'll add more details as I figure out where this is coming from.

**Comment by herbdool** [comment]
If I disable the module, then `book_prev()` doesn't get called at all on the main page, which makes sense. It is the first page so there's nothing previous.

**Comment by herbdool** [comment]
In `book_menus_preprocess_book_navigation_before()` it is doing this: `$variables['book_link']['plid'] = TRUE;` so that it "tricks book.module not to display the "up" link." But then in `book_prev()` it is checking that `$book_link['plid'] == 0` and existing early if so. Nothing has changed in `book_prev()` in like 15 years so perhaps this has been broken for awhile.

**Comment by herbdool** [comment]
@yorkshire-pudding I've got a PR and it seems to work. The main thing is that it doesn't attempt to create a previous link on the top page. Before and after, it wasn't creating that link, but before it was only because it couldn't do it and it was looking for empty variables. Now it skips the attempt which is better.

**Comment by herbdool** [comment]
BTW, I was thinking to use this module for helping display translated books better, but I think in either case, it seems that it's better to have translated books be completely separate even if the individual pages could be linked. Though maybe someone could get it to work if they also enable the translation of items in the menu settings. Might need i18n.

**Comment by yorkshire-pudding** [comment]
@herbdool - I'll give the PR a test, but I still can't figure out how to reproduce this.

What I normally do is use Menu Pager with the Book Menus Menu but I have added the Book Menu Navigation to the page and I don't see the warning.  Are you able to expand on Steps to Reproduce?  Thanks

**Comment by herbdool** [comment]
I found that I didn't need to add the Book Menu Navigation to see the warning. The only thing I had done was enable book, then created a new book; then enabled Book Menu and when viewing the book page I created, I saw the warning.

You could check too that the guard clause at the top of `book_prev()` is stopping it if it's the top page.

**Comment by yorkshire-pudding** [comment]
Issue reproduced and PR tested.  Thanks @herbdool - works a treat.
